/** RENU PRESS print product catalogue — consultant knowledge base */

export type CatalogProduct = {
  id: string;
  name: string;
  category: string;
  description: string;
  useCase: string;
  material: string;
  advantages: string[];
  suggestedQty: string;
  image: string;
  tags: string[];
  outdoor?: boolean;
  indoor?: boolean;
  premium?: boolean;
  economy?: boolean;
  weatherResistant?: boolean;
};

const img = (id: string, w = 800) =>
  `https://images.unsplash.com/${id}?w=${w}&q=75&auto=format&fit=crop`;

export const CATALOG: CatalogProduct[] = [
  {
    id: "flex-banner",
    name: "Flex Banner",
    category: "Outdoor",
    description: "High-visibility outdoor/indoor promotional banners.",
    useCase: "Offers, openings, events, roadside promotion",
    material: "Star / frontlit flex + eco solvent ink",
    advantages: ["Large size possible", "Fast production", "Cost-effective reach"],
    suggestedQty: "1–10 pcs",
    image: img("photo-1558618666-fcd25c85cd64"),
    tags: ["flex", "banner", "outdoor", "campaign", "shop", "election"],
    outdoor: true,
    economy: true,
    weatherResistant: true,
  },
  {
    id: "vinyl-banner",
    name: "Vinyl Banner",
    category: "Outdoor",
    description: "Durable vinyl for window & wall branding.",
    useCase: "Glass branding, storefront, vehicle side",
    material: "Vinyl / one-way vision options",
    advantages: ["Clean cut", "Indoor + outdoor", "Premium finish"],
    suggestedQty: "As per area (sq ft)",
    image: img("photo-1563986768494-4dee2763ff3f"),
    tags: ["vinyl", "window", "glass", "shop", "branding"],
    outdoor: true,
    indoor: true,
    weatherResistant: true,
  },
  {
    id: "star-flex",
    name: "Star Flex",
    category: "Outdoor",
    description: "Premium opacity flex for sharp outdoor print.",
    useCase: "Hoardings, long-term outdoor boards",
    material: "Star flex black-back",
    advantages: ["Better opacity", "Night readability with light", "Longer outdoor life"],
    suggestedQty: "1+ boards",
    image: img("photo-1542744173-8e7e53415bb0"),
    tags: ["star", "flex", "hoarding", "outdoor", "premium"],
    outdoor: true,
    premium: true,
    weatherResistant: true,
  },
  {
    id: "backlit-flex",
    name: "Backlit Flex",
    category: "Signage",
    description: "Translucent flex for light boxes.",
    useCase: "Glow boxes, night shop front",
    material: "Backlit flex + lightbox frame",
    advantages: ["Night visibility", "Premium look", "Brand presence 24×7"],
    suggestedQty: "1 lightbox set",
    image: img("photo-1441986300917-64674bd600d8"),
    tags: ["backlit", "glow", "lightbox", "shop", "restaurant"],
    outdoor: true,
    indoor: true,
    premium: true,
  },
  {
    id: "frontlit-flex",
    name: "Frontlit Flex",
    category: "Outdoor",
    description: "Standard front-lit outdoor flex media.",
    useCase: "General outdoor banners & boards",
    material: "Frontlit flex",
    advantages: ["Widely used", "Economical", "Good colour pop"],
    suggestedQty: "As needed",
    image: img("photo-1558618666-fcd25c85cd64"),
    tags: ["frontlit", "flex", "outdoor", "economy"],
    outdoor: true,
    economy: true,
  },
  {
    id: "acp-sign",
    name: "ACP Sign Board",
    category: "Signage",
    description: "Aluminium composite panel board for shop identity.",
    useCase: "Main shop name board, office fascia",
    material: "ACP + vinyl / acrylic letters option",
    advantages: ["Premium rigid look", "Long-term outdoor", "Weather resistant"],
    suggestedQty: "1 main board",
    image: img("photo-1486406146926-c627a92ad1ab"),
    tags: ["acp", "sign", "board", "shop", "office", "branding", "long-term"],
    outdoor: true,
    premium: true,
    weatherResistant: true,
  },
  {
    id: "glow-sign",
    name: "Glow Sign Board",
    category: "Signage",
    description: "Illuminated signage for night branding.",
    useCase: "Shop/restaurant night identity",
    material: "Acrylic face + LED / tube",
    advantages: ["High night visibility", "Attracts footfall", "Premium brand feel"],
    suggestedQty: "1 glow board",
    image: img("photo-1517248135467-4c7edcad34c4"),
    tags: ["glow", "sign", "shop", "restaurant", "led", "night"],
    outdoor: true,
    premium: true,
  },
  {
    id: "led-sign",
    name: "LED Sign Board",
    category: "Signage",
    description: "LED-based signage / digital-style presence.",
    useCase: "High-impact storefront, events",
    material: "LED modules / acrylic + LED",
    advantages: ["Bright", "Modern", "Strong recall"],
    suggestedQty: "1 unit",
    image: img("photo-1497366216548-37526070297c"),
    tags: ["led", "sign", "restaurant", "shop", "office", "premium"],
    outdoor: true,
    indoor: true,
    premium: true,
  },
  {
    id: "acrylic-sign",
    name: "Acrylic Sign Board",
    category: "Signage",
    description: "Clear/coloured acrylic letters & boards.",
    useCase: "Reception, clinic, boutique",
    material: "Acrylic sheet + stand-off / vinyl",
    advantages: ["Premium indoor look", "Clean edges", "Brand colour match"],
    suggestedQty: "1 reception set",
    image: img("photo-1497366811353-6870744d04b2"),
    tags: ["acrylic", "sign", "office", "indoor", "premium"],
    indoor: true,
    premium: true,
  },
  {
    id: "sunboard",
    name: "Sunboard",
    category: "Display",
    description: "Lightweight foam PVC board for displays.",
    useCase: "Indoor posters, stands, short campaigns",
    material: "Sunboard + vinyl paste",
    advantages: ["Light", "Easy mount", "Sharp print"],
    suggestedQty: "5–50 pcs",
    image: img("photo-1561070791-2526d30994b5"),
    tags: ["sunboard", "display", "indoor", "poster", "election"],
    indoor: true,
    economy: true,
  },
  {
    id: "foam-board",
    name: "Foam Board",
    category: "Display",
    description: "Foam core display boards.",
    useCase: "Exhibitions, school projects, menus",
    material: "Foam board",
    advantages: ["Ultra light", "Quick turnaround", "Indoor safe"],
    suggestedQty: "10+ pcs",
    image: img("photo-1586075010923-2dd4570fb338"),
    tags: ["foam", "board", "exhibition", "indoor"],
    indoor: true,
    economy: true,
  },
  {
    id: "canvas-print",
    name: "Canvas Print",
    category: "Photo",
    description: "Gallery-wrap canvas for photos & art.",
    useCase: "Home, office décor, gifts",
    material: "Canvas fabric + stretch frame",
    advantages: ["Premium gift", "No glass glare", "Long display life"],
    suggestedQty: "1–10 pcs",
    image: img("photo-1579783902614-a3fb3927b6a5"),
    tags: ["canvas", "photo", "gift", "frame", "premium"],
    indoor: true,
    premium: true,
  },
  {
    id: "photo-print",
    name: "Photo Print",
    category: "Photo",
    description: "High-quality photo paper prints.",
    useCase: "Events, family, studio",
    material: "Glossy / matt photo paper",
    advantages: ["True colour", "Multiple sizes", "Fast"],
    suggestedQty: "10–100+",
    image: img("photo-1452587925148-ce544e77e70d"),
    tags: ["photo", "print", "wedding", "gift"],
    indoor: true,
    economy: true,
  },
  {
    id: "photo-frame",
    name: "Photo Frame",
    category: "Photo",
    description: "Framed photo presentation.",
    useCase: "Gifts, office, wedding memories",
    material: "Frame + glass/acrylic + print",
    advantages: ["Ready to gift", "Premium unboxing", "Multiple sizes"],
    suggestedQty: "1–20",
    image: img("photo-1513519245088-0e12902e35ca"),
    tags: ["frame", "photo", "gift", "wedding"],
    indoor: true,
  },
  {
    id: "visiting-card",
    name: "Visiting Card",
    category: "Stationery",
    description: "Professional visiting cards.",
    useCase: "Networking, sales, shop counter",
    material: "300–350 GSM + matt/gloss/spot UV",
    advantages: ["First impression", "Brand consistency", "Low unit cost at qty"],
    suggestedQty: "500 / 1000 pcs",
    image: img("photo-1589939705384-5185137a7f0f"),
    tags: ["visiting", "business", "card", "shop", "office", "restaurant", "stationery"],
    indoor: true,
    economy: true,
  },
  {
    id: "business-card",
    name: "Business Card",
    category: "Stationery",
    description: "Premium business cards with finishes.",
    useCase: "Corporate teams, consultants",
    material: "Texture / UV / foil options",
    advantages: ["Premium feel", "Team sets", "Brand hierarchy"],
    suggestedQty: "500+",
    image: img("photo-1589939705384-5185137a7f0f"),
    tags: ["business", "card", "corporate", "premium"],
    premium: true,
  },
  {
    id: "pvc-card",
    name: "PVC Card",
    category: "ID",
    description: "Durable plastic cards.",
    useCase: "Membership, access, loyalty",
    material: "PVC CR80",
    advantages: ["Waterproof", "Long life", "Photo print ready"],
    suggestedQty: "50–500",
    image: img("photo-1611532736597-de2d4265fba3"),
    tags: ["pvc", "card", "id", "school", "office"],
  },
  {
    id: "id-card",
    name: "ID Card",
    category: "ID",
    description: "Employee / student ID with photo.",
    useCase: "Schools, factories, events",
    material: "PVC + lanyard / holder",
    advantages: ["Security", "Professional", "Bulk ready"],
    suggestedQty: "50–2000",
    image: img("photo-1611532736597-de2d4265fba3"),
    tags: ["id", "card", "school", "office", "staff"],
  },
  {
    id: "wedding-card",
    name: "Wedding Card",
    category: "Wedding",
    description: "Invitation cards for weddings.",
    useCase: "Shaadi invitations",
    material: "Premium paper + insert options",
    advantages: ["Custom design", "Matching envelope", "Guest-ready packs"],
    suggestedQty: "100–500",
    image: img("photo-1464366400600-7168b8af9bc3"),
    tags: ["wedding", "invitation", "card", "shaadi"],
    premium: true,
  },
  {
    id: "invitation-card",
    name: "Invitation Card",
    category: "Events",
    description: "Event & function invitations.",
    useCase: "Parties, inaugurations, ceremonies",
    material: "Card stock + finish",
    advantages: ["Branded invite", "RSVP friendly", "Photo options"],
    suggestedQty: "50–300",
    image: img("photo-1464366400600-7168b8af9bc3"),
    tags: ["invitation", "event", "card"],
  },
  {
    id: "certificate",
    name: "Certificate",
    category: "Stationery",
    description: "Awards & completion certificates.",
    useCase: "Schools, training, corporate",
    material: "Certificate paper + border design",
    advantages: ["Formal look", "Serial options", "Bulk print"],
    suggestedQty: "50–500",
    image: img("photo-1434030216411-0b793f4b4173"),
    tags: ["certificate", "school", "award", "office"],
  },
  {
    id: "bill-book",
    name: "Bill Book",
    category: "Stationery",
    description: "Carbon / multi-copy bill books.",
    useCase: "Retail billing, shops",
    material: "NCR / carbon paper books",
    advantages: ["GST ready layout", "Duplicate copies", "Shop essential"],
    suggestedQty: "10–50 books",
    image: img("photo-1554224155-6726b3ff858f"),
    tags: ["bill", "book", "shop", "restaurant", "invoice", "stationery"],
    economy: true,
  },
  {
    id: "receipt-book",
    name: "Receipt Book",
    category: "Stationery",
    description: "Payment receipt books.",
    useCase: "Collections, fees, services",
    material: "NCR books",
    advantages: ["Serial numbers", "Duplicate", "Professional"],
    suggestedQty: "10+ books",
    image: img("photo-1554224155-6726b3ff858f"),
    tags: ["receipt", "book", "office", "shop"],
  },
  {
    id: "letterhead",
    name: "Letterhead",
    category: "Stationery",
    description: "Official letterheads.",
    useCase: "Office correspondence",
    material: "70–100 GSM bond",
    advantages: ["Brand authority", "A4 standard", "Matching envelope option"],
    suggestedQty: "500–1000",
    image: img("photo-1586075010923-2dd4570fb338"),
    tags: ["letterhead", "office", "corporate", "stationery"],
  },
  {
    id: "brochure",
    name: "Brochure",
    category: "Marketing",
    description: "Folded product / service brochures.",
    useCase: "Sales kits, exhibitions",
    material: "170–300 GSM art paper",
    advantages: ["Full story in one piece", "Portable", "Premium finish"],
    suggestedQty: "500–5000",
    image: img("photo-1561070791-2526d30994b5"),
    tags: ["brochure", "marketing", "corporate", "catalogue"],
  },
  {
    id: "catalogue",
    name: "Catalogue",
    category: "Marketing",
    description: "Multi-page product catalogues.",
    useCase: "Wholesale, showrooms",
    material: "Art paper + binding",
    advantages: ["SKU showcase", "Long shelf life", "Sales tool"],
    suggestedQty: "100–1000",
    image: img("photo-1544947950-fa07a98d237f"),
    tags: ["catalogue", "marketing", "shop", "wholesale"],
  },
  {
    id: "flyer",
    name: "Flyer",
    category: "Marketing",
    description: "Single-sheet promotional flyers.",
    useCase: "Offers, launches, campaigns",
    material: "90–170 GSM",
    advantages: ["Mass distribution", "Low cost per lead", "Fast print"],
    suggestedQty: "1000–10000",
    image: img("photo-1561070791-2526d30994b5"),
    tags: ["flyer", "pamphlet", "election", "marketing", "offer"],
    economy: true,
  },
  {
    id: "pamphlet",
    name: "Pamphlet",
    category: "Marketing",
    description: "Informative pamphlets for outreach.",
    useCase: "Political / awareness / education",
    material: "Maplitho / art paper",
    advantages: ["Detailed message", "Door-to-door friendly", "Bulk economical"],
    suggestedQty: "2000+",
    image: img("photo-1454165804606-c3d57bc86b40"),
    tags: ["pamphlet", "election", "campaign", "school"],
    economy: true,
  },
  {
    id: "poster",
    name: "Poster",
    category: "Marketing",
    description: "Wall / board posters.",
    useCase: "Events, elections, promotions",
    material: "Maplitho / art paper / flex",
    advantages: ["Big visual", "Quick awareness", "Multiple sizes"],
    suggestedQty: "100–5000",
    image: img("photo-1492684223066-81342ee5ff30"),
    tags: ["poster", "election", "event", "marketing"],
  },
  {
    id: "sticker",
    name: "Sticker",
    category: "Labels",
    description: "Die-cut or sheet stickers.",
    useCase: "Packaging, branding, campaigns",
    material: "Vinyl / paper sticker",
    advantages: ["Versatile", "Waterproof options", "Any shape"],
    suggestedQty: "500–5000",
    image: img("photo-1618005182384-a83a8bd57fbe"),
    tags: ["sticker", "label", "shop", "packaging", "election", "restaurant"],
    economy: true,
  },
  {
    id: "label",
    name: "Label",
    category: "Labels",
    description: "Product packaging labels.",
    useCase: "Bottles, boxes, garments tags",
    material: "Adhesive label stock",
    advantages: ["Barcode ready", "Brand consistency", "Bulk rolls/sheets"],
    suggestedQty: "1000+",
    image: img("photo-1607083206869-4c7672e72a8a"),
    tags: ["label", "packaging", "shop", "product"],
  },
  {
    id: "packaging-box",
    name: "Packaging Box",
    category: "Packaging",
    description: "Custom printed packaging boxes.",
    useCase: "Retail products, takeaway, gifts",
    material: "Corrugated / duplex carton",
    advantages: ["Unboxing experience", "Protects product", "Brand story"],
    suggestedQty: "500+",
    image: img("photo-1607083206869-4c7672e72a8a"),
    tags: ["packaging", "box", "shop", "restaurant", "gift"],
  },
  {
    id: "paper-bag",
    name: "Paper Bag",
    category: "Packaging",
    description: "Branded paper carry bags.",
    useCase: "Retail, boutique, restaurant",
    material: "Kraft / art paper bag",
    advantages: ["Eco-friendly image", "Walking advertisement", "Reusable feel"],
    suggestedQty: "500–5000",
    image: img("photo-1607083206968-13611e3d76db"),
    tags: ["paper", "bag", "carry", "shop", "restaurant", "shopping"],
  },
  {
    id: "carry-bag",
    name: "Carry Bag",
    category: "Packaging",
    description: "Non-woven / cloth carry bags.",
    useCase: "Retail, events, campaigns",
    material: "Non-woven / cotton options",
    advantages: ["Reusable", "Large print area", "Campaign giveaway"],
    suggestedQty: "500+",
    image: img("photo-1607083206968-13611e3d76db"),
    tags: ["carry", "bag", "shop", "election", "event"],
  },
  {
    id: "tshirt",
    name: "T-Shirt Printing",
    category: "Apparel",
    description: "Custom tee branding.",
    useCase: "Staff uniform, campaigns, events",
    material: "Cotton / poly + DTF / screen / vinyl",
    advantages: ["Walking brand", "Team identity", "Campaign recall"],
    suggestedQty: "20–500+",
    image: img("photo-1521572163474-6864f9cf17ab"),
    tags: ["tshirt", "t-shirt", "apparel", "staff", "election", "restaurant", "uniform"],
  },
  {
    id: "hoodie",
    name: "Hoodie Printing",
    category: "Apparel",
    description: "Branded hoodies.",
    useCase: "Premium merch, teams, winters",
    material: "Fleece + print/embroidery",
    advantages: ["Premium gift", "Staff pride", "Long wear"],
    suggestedQty: "10–100",
    image: img("photo-1556821840-3a63f95609a7"),
    tags: ["hoodie", "apparel", "premium", "corporate"],
    premium: true,
  },
  {
    id: "cap",
    name: "Cap Printing",
    category: "Apparel",
    description: "Custom caps.",
    useCase: "Staff, campaigns, events",
    material: "Cotton cap + embroidery/print",
    advantages: ["Outdoor visibility", "Giveaway hit", "Uniform set"],
    suggestedQty: "50–500",
    image: img("photo-1588850561407-ed78c282e89b"),
    tags: ["cap", "election", "staff", "restaurant", "campaign"],
  },
  {
    id: "mug",
    name: "Mug Printing",
    category: "Gifts",
    description: "Sublimation / printed mugs.",
    useCase: "Corporate gifts, cafes",
    material: "Ceramic + sublimation",
    advantages: ["Daily brand recall", "Gift ready", "Photo print"],
    suggestedQty: "12–100+",
    image: img("photo-1514228742587-6b1558fcca3d"),
    tags: ["mug", "gift", "corporate", "cafe"],
  },
  {
    id: "bottle",
    name: "Bottle Printing",
    category: "Gifts",
    description: "Branded bottles.",
    useCase: "Corporate kits, events",
    material: "Steel / plastic + print",
    advantages: ["Useful gift", "Logo always visible", "Event kit staple"],
    suggestedQty: "25–200",
    image: img("photo-1602143407151-7111542de6e8"),
    tags: ["bottle", "gift", "corporate", "event"],
  },
  {
    id: "keychain",
    name: "Keychain",
    category: "Gifts",
    description: "Custom keychains.",
    useCase: "Giveaways, openings",
    material: "Acrylic / metal / PVC",
    advantages: ["Low cost recall", "Bulk friendly", "Logo always with customer"],
    suggestedQty: "100–1000",
    image: img("photo-1618005182384-a83a8bd57fbe"),
    tags: ["keychain", "gift", "shop", "opening"],
    economy: true,
  },
  {
    id: "corporate-gifts",
    name: "Corporate Gifts",
    category: "Gifts",
    description: "Assorted branded gift sets.",
    useCase: "Client gifting, festivals",
    material: "Mixed print products",
    advantages: ["Relationship building", "Bundle value", "Custom kits"],
    suggestedQty: "Kit-based",
    image: img("photo-1513885535751-8b9238bd345a"),
    tags: ["corporate", "gifts", "office", "premium"],
    premium: true,
  },
  {
    id: "awards",
    name: "Awards",
    category: "Awards",
    description: "Custom awards & trophies base print.",
    useCase: "Functions, sports, corporate",
    material: "Acrylic / metal / wood options",
    advantages: ["Recognition moment", "Photo-worthy", "Custom engraving"],
    suggestedQty: "5–50",
    image: img("photo-1567427017947-545c5f8d16ad"),
    tags: ["award", "trophy", "medal", "school", "corporate"],
  },
  {
    id: "trophies",
    name: "Trophies",
    category: "Awards",
    description: "Event trophies.",
    useCase: "Sports & competitions",
    material: "Metal / plastic / acrylic",
    advantages: ["Stage ready", "Bulk sets", "Custom plates"],
    suggestedQty: "10–100",
    image: img("photo-1567427017947-545c5f8d16ad"),
    tags: ["trophy", "award", "school", "event"],
  },
  {
    id: "medals",
    name: "Medals",
    category: "Awards",
    description: "Custom medals with ribbon.",
    useCase: "Sports meets, schools",
    material: "Metal medal + ribbon",
    advantages: ["Participant pride", "Bulk economical", "Logo centre"],
    suggestedQty: "50–500",
    image: img("photo-1567427017947-545c5f8d16ad"),
    tags: ["medal", "school", "sports", "award"],
  },
  {
    id: "office-branding",
    name: "Office Branding",
    category: "Branding",
    description: "Full office visual identity set.",
    useCase: "Reception, cabins, glass",
    material: "Vinyl, acrylic, sunboard mix",
    advantages: ["Professional space", "Visitor trust", "Consistent brand"],
    suggestedQty: "Package",
    image: img("photo-1497366216548-37526070297c"),
    tags: ["office", "branding", "glass", "wall"],
    indoor: true,
    premium: true,
  },
  {
    id: "vehicle-branding",
    name: "Vehicle Branding",
    category: "Branding",
    description: "Car / auto / fleet wraps & vinyl.",
    useCase: "Delivery, sales, campaign vehicles",
    material: "Cast/calendered vinyl",
    advantages: ["Mobile billboard", "Route coverage", "Strong recall"],
    suggestedQty: "1 vehicle+",
    image: img("photo-1449965408869-eaa3f722e40d"),
    tags: ["vehicle", "car", "branding", "election", "delivery", "fleet"],
    outdoor: true,
    weatherResistant: true,
  },
  {
    id: "wall-graphics",
    name: "Wall Graphics",
    category: "Branding",
    description: "Large format wall vinyl / murals.",
    useCase: "Showroom, cafe, office walls",
    material: "Wall vinyl / canvas murals",
    advantages: ["Immersive brand", "Photo spots", "Indoor impact"],
    suggestedQty: "As per wall area",
    image: img("photo-1497366754035-f200968a6e72"),
    tags: ["wall", "graphics", "office", "restaurant", "shop"],
    indoor: true,
  },
  {
    id: "glass-branding",
    name: "Glass Branding",
    category: "Branding",
    description: "Frosted / printed glass films.",
    useCase: "Office partitions, shop glass",
    material: "Frosted / printed vinyl",
    advantages: ["Privacy + brand", "Modern look", "Easy update"],
    suggestedQty: "As per glass area",
    image: img("photo-1497366811353-6870744d04b2"),
    tags: ["glass", "window", "vinyl", "office", "shop"],
    indoor: true,
  },
  {
    id: "table-tent",
    name: "Table Tent",
    category: "Restaurant",
    description: "Table-top promo stands.",
    useCase: "Menus, offers, QR",
    material: "Tent card / acrylic stand",
    advantages: ["Order-time visibility", "Upsell offers", "QR menu ready"],
    suggestedQty: "20–100",
    image: img("photo-1517248135467-4c7edcad34c4"),
    tags: ["table", "tent", "restaurant", "menu", "qr"],
    indoor: true,
  },
  {
    id: "menu-card",
    name: "Menu Card",
    category: "Restaurant",
    description: "Printed restaurant menus.",
    useCase: "Dine-in menus",
    material: "Art card + lamination",
    advantages: ["Clear pricing layout", "Photo dishes", "Durable lamination"],
    suggestedQty: "20–200",
    image: img("photo-1414235077428-338989a2e8c0"),
    tags: ["menu", "restaurant", "cafe", "card"],
    indoor: true,
  },
  {
    id: "qr-stand",
    name: "Google Review QR Stand",
    category: "Retail",
    description: "QR stand for reviews & digital menu.",
    useCase: "Counters, tables",
    material: "Acrylic / sunboard stand",
    advantages: ["More reviews", "Modern trust", "Low cost high impact"],
    suggestedQty: "2–10",
    image: img("photo-1556740749-887f6717d7e4"),
    tags: ["qr", "review", "shop", "restaurant", "stand"],
    indoor: true,
  },
  {
    id: "price-tag",
    name: "Price Tags",
    category: "Retail",
    description: "Garment / product price tags.",
    useCase: "Clothing & retail",
    material: "Card tags + string/clip",
    advantages: ["Shelf ready", "Brand on every piece", "Bulk cheap"],
    suggestedQty: "500–5000",
    image: img("photo-1441986300917-64674bd600d8"),
    tags: ["price", "tag", "clothing", "shop", "retail"],
    economy: true,
  },
  {
    id: "flag",
    name: "Campaign Flag",
    category: "Campaign",
    description: "Political / event flags.",
    useCase: "Rallies, stages, streets",
    material: "Polyester / flex flags",
    advantages: ["Mass visibility", "Wave motion attention", "Bulk"],
    suggestedQty: "100+",
    image: img("photo-1529107386315-e1a2ed48a620"),
    tags: ["flag", "election", "campaign", "political"],
    outdoor: true,
  },
  {
    id: "stage-backdrop",
    name: "Stage Backdrop",
    category: "Events",
    description: "Large seamless stage flex.",
    useCase: "Political stage, weddings, events",
    material: "Star flex / fabric backdrop",
    advantages: ["Photo background", "Brand frame", "Large format"],
    suggestedQty: "1 set",
    image: img("photo-1492684223066-81342ee5ff30"),
    tags: ["stage", "backdrop", "election", "wedding", "event"],
    outdoor: true,
    indoor: true,
  },
  {
    id: "badge",
    name: "Badge",
    category: "Campaign",
    description: "Pin / sticker badges.",
    useCase: "Campaigns, events, staff",
    material: "Tin / acrylic / sticker badge",
    advantages: ["Wearable brand", "Giveaway", "Bulk"],
    suggestedQty: "500+",
    image: img("photo-1618005182384-a83a8bd57fbe"),
    tags: ["badge", "election", "event", "campaign"],
    economy: true,
  },
  {
    id: "delivery-bag",
    name: "Delivery Bag Branding",
    category: "Restaurant",
    description: "Branded food delivery bags.",
    useCase: "Cloud kitchen / restaurant delivery",
    material: "Paper / non-woven bag",
    advantages: ["Every order markets you", "Hygiene look", "Local recall"],
    suggestedQty: "500+",
    image: img("photo-1607083206968-13611e3d76db"),
    tags: ["delivery", "bag", "restaurant", "food"],
  },
  {
    id: "hoarding",
    name: "Hoarding / Political Banner",
    category: "Outdoor",
    description: "Large format outdoor campaign boards.",
    useCase: "Elections, city branding",
    material: "Star flex + frame mount",
    advantages: ["Maximum reach", "Long distance read", "Campaign staple"],
    suggestedQty: "Multiple locations",
    image: img("photo-1558618666-fcd25c85cd64"),
    tags: ["hoarding", "election", "political", "banner", "outdoor"],
    outdoor: true,
    weatherResistant: true,
  },
  {
    id: "custom-printing",
    name: "Custom Printing",
    category: "Custom",
    description: "Any special print job not in standard list.",
    useCase: "Unique requirements",
    material: "As per brief",
    advantages: ["Flexible", "Team consults", "Tailored solution"],
    suggestedQty: "As required",
    image: img("photo-1563986768494-4dee2763ff3f"),
    tags: ["custom", "any", "special"],
  },
];

export function getProductById(id: string) {
  return CATALOG.find((p) => p.id === id);
}

export function getProductByName(name: string) {
  const n = name.toLowerCase();
  return CATALOG.find((p) => p.name.toLowerCase() === n || p.id === n);
}
